backend:
  name: github
  repo: kentaro-okada/okada-hugo-universal-theme-master
  branch: master # Branch to update

publish_mode: editorial_workflow
 
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
 
collections:
  - name: "post"
    label: "Post"
    folder: "content/posts"
    create: true
    slug: "{{slug}}-{{year}}{{month}}{{day}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Descreption", name: "description", widget: "text"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Category", name: "categories", widget: "list", required: true}
      - {label: "Tags", name: "tags", widget: "list", required: true}
      - {label: "Body", name: "body", widget: "markdown"}
